apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: brief-ocp-api
  labels:
    app: brief-ocp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brief-ocp-api
  serviceName: brief-ocp-api
  template:
    metadata:
      labels:
        app: brief-ocp-api
    spec:
      containers:
      - name: brief-ocp-api
        image: quay.cloudmgmt.mutua.es/middleware-develop/thanos_mm:v0.1
        resources:
          limits:
            memory: 2G
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 50m
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        configMap:
          name: brief-ocp-api-src